qiime2/q2studio

app/js/actions/connection.js, app/js/actions/plugins.js, app/js/components/Loading.jsx, app/js/components/pages/App.jsx, app/js/components/pages/Flow.jsx, app/js/containers/Loading.js, app/js/main.jsx, app/js/reducers/connection.js, app/js/reducers/index.js, app/js/reducers/plugins.js, package.json, test/reducer_spec.js
Workflow URIs are now a piece of data sent back with the response from the server, allowing server-side API route changes to work on the client-side without modification, granted the response remains the same.
HMAC now uses all pieces of required data for the hash message.
All necessary workflow data is pulled from the server now, and populated in the the UI.
=> Initialize HMAC auth between server/client. Load data through dynamic uris provided by server

app/js/containers/PluginsList.js
I'm not sure if this is the best place to put this, but things will probably move around anyways.
@jakereps can you review?
=> Filter out plugins without workflows

app/main.js
@jakereps @Kleptobismol can you review?
=> BUG: REST API now spawned in conda env correctly

app/js/actions/artifacts.js, app/js/actions/jobs.js, app/js/actions/plugins.js, app/js/reducers/artifacts.js, qiime_studio/api/security.py, qiime_studio/api/v1.py
Very minor changes to make artifacts consistent with working directory in multiple contexts (job, initial load, etc)
@Kleptobismol @jakereps can you review?
=> BUG: fixed artifact reloading to depend on directory

app/js/components/Plugins.jsx, app/js/components/pages/App.jsx, package.json
=> Changes PluginList to accordion grouped by plugin

app/js/actions/artifacts.js, app/js/actions/jobs.js, app/js/actions/plugins.js, app/js/actions/types.js, app/js/components/Artifacts.jsx, app/js/components/ArtifactsListFrame.jsx, app/js/components/JobListFrame.jsx, app/js/components/Plugins.jsx, app/js/components/Tabs.jsx, app/js/components/Workflows.jsx, app/js/containers/Job.js, app/js/containers/Workflows.js, app/js/reducers/jobs.js, app/js/reducers/plugins.js, app/js/reducers/tabstate.js, app/js/util/auth.js, test/reducer_spec.js
=> LINT: Fix lint errors/tests

app/main.js
=> BUG: Fixed window open on built version

app/css/Visualization.css, app/css/main.css, app/js/actions/artifacts.js, app/js/actions/currentdirectory.js, app/js/components/ArtifactsListFrame.jsx, app/js/components/Metadata.jsx, app/js/components/MetadataFile.jsx, app/js/components/Visualization.jsx, app/js/components/pages/Job.jsx, app/js/containers/ArtifactsList.js, app/js/containers/Job.js, app/js/reducers/artifacts.js, app/js/util/auth.js, config/eslint.yaml, qiime_studio/__main__.py, qiime_studio/api/jobs.py, qiime_studio/api/plugins.py, qiime_studio/api/workspace.py, test/reducer_spec.js
Does some awful things, but we don't have time to fix it right now.
Make visualizations a little cleaner and add support for Choices predicate.
=> ENH: Support metadata/metadataCategory

app/js/actions/artifacts.js, app/js/actions/currentdirectory.js, app/js/components/ArtifactGenerator.jsx, app/js/components/Artifacts.jsx, app/js/containers/ArtifactGenerator.js, app/js/reducers/artifacts.js, app/js/reducers/tabstate.js, app/main.js, qiime_studio/api/workspace.py
=> Adds an Artifact creation interface

qiime_studio/api/jobs.py, qiime_studio/api/workspace.py, qiime_studio/util.py
I think I covered every place that was previously open to errors. To stop `try:except:` redundancy I just made it into a decorator.
Fixes #71
=> FIX: Improve error handling

app/js/components/pages/Job.jsx, qiime_studio/api/plugins.py
Resolves #79 
Tested using a new [`q2-test-plugin`](https://github.com/jakereps/q2-test-plugin) method.
=> ENH: Add default value support

app/js/components/JobRunning.jsx, qiime_studio/api/jobs.py, qiime_studio/util.py
pair-programmed with @jairideout and @ebolyen
=> ENH: ports and improves redirected_stdio

qiime_studio/api/workspace.py
=> MAINT: updates for new peek behavior

app/js/components/pages/Job.jsx, app/js/containers/Job.js, qiime_studio/api/jobs.py
=> ENH: Add support for Bool type

README.md
Emphasize user installation instructions are on the website, and visually separate dev installation instructions.
=> MAINT: Add prototype disclaimer to README

.travis.yml, app/js/actions/artifacts.js, app/js/containers/Job.js
=> BUG: Error message on `fetchAPI` calls not being displayed properly

package.json, setup.py
Do not merge until we are ready to release.
=> REL: Promote 2017.2.0.dev0 to 2017.2.0

app/js/actions/artifacts.js, app/js/components/ArtifactDetail.jsx, app/js/containers/ArtifactDetail.js, q2studio/api/workspace.py
=> ENH: Add export functionality from Artifact detail page

q2studio/api/formats.py
Fixes [my PR from yesterday](https://github.com/qiime2/q2studio/pull/120) to work with the [latest changes to the importable formats feature](https://github.com/qiime2/qiime2/pull/275) per @jairideout 's comment.
=> ENH: importable formats feature w/ update to qiime API

app/js/components/JobHistoryData.jsx, app/js/components/pages/Job.jsx, app/js/containers/Job.js, q2studio/api/jobs.py, q2studio/api/plugins.py, q2studio/api/workspace.py
This is disgusting. But it seems to work.
depends on https://github.com/qiime2/qiime2/pull/286
Fixes #119
=> MAINT: support optional parameters

README.md, package.json
=> MAINT: updating project description

setup.py
=> DEP: fix QIIME 2 version

app/index.html
=> MAINT: Embedded prototype warnings

app/js/components/Metadata.jsx, app/js/components/pages/Job.jsx, q2studio/api/jobs.py
The approach taken here more or less matches how q2cli handles the new Metadata functionality.
=> MAINT: new Metadata updates

.travis.yml, Makefile, app/js/components/ArtifactGenerator.jsx, app/js/containers/ArtifactGenerator.js, q2studio/api/__init__.py, q2studio/api/formats.py, q2studio/api/types.py, q2studio/api/workspace.py, q2studio/server.py, q2studio/tests/__init__.py, q2studio/tests/test_studio.py
The single quotes were causing an error, `BAD REQUEST - Unknown expression: <class ‘_ast.Str’>` when using the import gui.  The single quoted importable type was being passed into `Artifact.import_data` in [workspace.create_artifact](https://github.com/qiime2/q2studio/blob/master/q2studio/api/workspace.py#L81 ) which I think is where the error was bubbling up from.
[forum xr](https://forum.qiime2.org/t/importing-directory/14482).
=> Fix importing

setup.py
Completes 2022.2 dev bump, initial PR preemptively merged here: https://github.com/qiime2/q2studio/pull/203
=> maint: 2022.2 dev bump
